### ISSUE TITLE
Printing Schedule page prints large headers over top of each page

### ISSUE THREAD

**Issue by leeperkins** [RevolutionVA/website2017-app#16]
I am using Chrome 58.0.3029.96 on Windows 10.  I navigated to https://dev.revolutionconf.com/schedule, right-clicked on the page and selected `Print...`.  The preview that opened shows very large font headers over top of the schedule on each page.

![image](https://cloud.githubusercontent.com/assets/22798703/25854425/eae5babe-349d-11e7-89f1-47befdc7a394.png)

**Comment by iambriansreed** [comment]
@leeperkins While not perfect this should be resolved.
